name: Publish daily

on:
  schedule:
    - cron: "58 5 * * *"
  workflow_dispatch:
    inputs:
      ref:
        description: mdn/content commit to publish a release from
        required: false
        type: string
      dryRun:
        description: Don't actually publish to npm
        required: false
        type: boolean

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
          registry-url: "https://registry.npmjs.org"

      - run: npm ci

      - run: |
          if [ -n "$REF" ]; then
            npm run build -- --ref="$REF"
          else
            npm run build
          fi
        env:
          GH_TOKEN: ${{ github.token }}
          REF: ${{ inputs.ref }}

      - if: ${{ inputs.dryRun }}
        run: npm run publish:dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - if: ${{ ! inputs.dryRun }}
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: npm info @ddbeck/mdn-content-inventory
